# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "bda3ed61fc6c0c461d7e08bb6cb9017e"
name = "ahmed-rushrr-app"
handle = "ahmed-rushrr-app"
application_url = "https://cubic-veterans-database-girlfriend.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2024-10"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_orders,customer_read_orders,write_orders,write_products"

[auth]
redirect_urls = ["https://cubic-veterans-database-girlfriend.trycloudflare.com/auth/callback", "https://cubic-veterans-database-girlfriend.trycloudflare.com/auth/shopify/callback", "https://cubic-veterans-database-girlfriend.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
