# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "faf615d38856b0812abbad4d3b7f2e30"
name = "Testing-Logistic-app"
handle = "testing-logistic-app"
application_url = "https://sponsor-bridal-sleeping-correct.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products, read_orders, write_orders"

[auth]
redirect_urls = ["https://sponsor-bridal-sleeping-correct.trycloudflare.com/auth/callback", "https://sponsor-bridal-sleeping-correct.trycloudflare.com/auth/shopify/callback", "https://sponsor-bridal-sleeping-correct.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
